# Global plugins configuration
[[plugins]]
  package = "netlify-build-plugin-pushover"
  # Default inputs can go here if applicable

    [plugins.inputs]
        successMessage="Bhai app deploy ho gya!!!ğŸš€"
        errorMessage="Bhai Build phat gya!!!ğŸ˜"
        
# Production context:
[context.production]

  [[context.production.plugins]]
    package = "netlify-build-plugin-pushover"

      [context.production.plugins.inputs]
        successMessage="Bhai app deploy ho gya!!!ğŸš€"
        errorMessage="Bhai Build phat gya!!!ğŸ˜"


# Deploy Preview context:
[context.deploy-preview]

  [[context.deploy-preview.plugins]]
    package = "netlify-build-plugin-pushover"

      [context.deploy-preview.plugins.inputs]
        successMessage="Bhai app deploy ho gya!!!ğŸš€"
        errorMessage="Bhai Build phat gya!!!ğŸ˜"